// src/constants/cursosData.ts
// Catálogo maestro de cursos con esquema relacional completo para Base de Datos / Supabase / SQLite

import { Curso } from '../types/curso';

export const CURSOS_MOCK: Curso[] = [
  {
    id: '1',
    codigo: 'ANDES-RN-01',
    titulo: 'Desarrollo de Apps Móviles con React Native & Expo',
    subtitulo: 'Aprende a construir aplicaciones escalables para Android e iOS con TypeScript',
    nivel: 'Principiante',
    rating: 4.9,
    totalResenas: 142,
    duracion: '120 hrs',
    totalHorasAcademicas: 120,
    docente: 'Exar Williams Atao',
    docenteBio: 'Especialista en React Native, Expo SDK y arquitecturas multiplataforma con backend en la nube.',
    inversion: 149.90,
    precioRegular: 250.00,
    moneda: 'PEN',
    categoria: 'Móvil',
    modalidad: 'Virtual en vivo',
    imagenUrl: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=800',
    descripcion: 'Aprende a construir aplicaciones móviles escalables para Android e iOS con React Native, Expo SDK 57 y TypeScript desde cero.',
    requisitos: [
      'Fundamentos de JavaScript / TypeScript',
      'Computadora con Windows, Mac o Linux',
      'Smartphone Android o iPhone con Expo Go instalado',
    ],
    temario: [
      'Módulo 01: Arquitectura Móvil y Expo CLI',
      'Módulo 02: Componentes Core y Estilos con Flexbox',
      'Módulo 03: Listas Dinámicas y Optimización de FlatList',
      'Módulo 04: Enrutamiento Declarativo con Expo Router',
      'Módulo 05: Estado Global con Context API y React Hooks',
      'Módulo 06: Persistencia Local y Arquitectura Offline First',
    ],
    fechaInicio: '16 de Agosto',
    estado: 'disponible',
    creadoEn: '2026-08-01T00:00:00Z',
    actualizadoEn: '2026-09-30T00:00:00Z',
  },
  {
    id: '2',
    codigo: 'ANDES-BE-02',
    titulo: 'Backend en la Nube y PostgreSQL con Supabase',
    subtitulo: 'Diseño relacional, consultas en tiempo real y seguridad con Row Level Security',
    nivel: 'Intermedio',
    rating: 4.8,
    totalResenas: 98,
    duracion: '80 hrs',
    totalHorasAcademicas: 80,
    docente: 'Exar Williams Atao',
    docenteBio: 'Arquitecto Cloud y Backend Developer con enfoque en PostgreSQL y arquitecturas Serverless.',
    inversion: 129.90,
    precioRegular: 200.00,
    moneda: 'PEN',
    categoria: 'Backend',
    modalidad: 'Virtual en vivo',
    imagenUrl: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800',
    descripcion: 'Diseño de base de datos relacional, consultas CRUD en tiempo real y seguridad de datos con Row Level Security (RLS).',
    requisitos: [
      'Conocimientos básicos de SQL',
      'Estructuras de datos en formato JSON',
      'Consumo básico de APIs REST',
    ],
    temario: [
      'Modelado de Tablas y Relaciones Foreign Key',
      'Políticas de Seguridad RLS en PostgreSQL',
      'Suscripciones WebSocket en Tiempo Real',
      'Autenticación OAuth y JWT con Supabase Auth',
    ],
    fechaInicio: '20 de Agosto',
    estado: 'disponible',
    creadoEn: '2026-08-05T00:00:00Z',
    actualizadoEn: '2026-09-30T00:00:00Z',
  },
  {
    id: '3',
    codigo: 'ANDES-PAY-03',
    titulo: 'Pasarela de Pagos (Yape/Plin) & Boletas Digitales',
    subtitulo: 'Integración de billeteras digitales peruanas y facturación electrónica SUNAT',
    nivel: 'Avanzado',
    rating: 5.0,
    totalResenas: 84,
    duracion: '60 hrs',
    totalHorasAcademicas: 60,
    docente: 'Exar Williams Atao',
    docenteBio: 'Consultor FinTech en pasarelas de pago peruanas y sistemas de emisión de comprobantes digitales.',
    inversion: 139.90,
    precioRegular: 220.00,
    moneda: 'PEN',
    categoria: 'Pagos',
    modalidad: 'Virtual en vivo',
    imagenUrl: 'https://images.unsplash.com/photo-1556742049-0a67e5572240?w=800',
    descripcion: 'Generación dinámica de Códigos QR para billeteras digitales peruanas, validación de vouchers bancarios y cálculo de IGV (18%).',
    requisitos: [
      'React Native nivel intermedio',
      'Manejo de estado global en React',
      'Comprensión del flujo de pago digital',
    ],
    temario: [
      'Generación dinámica de Códigos QR',
      'Validación de comprobantes y transferencias CCI',
      'Cálculo automático de base imponible e IGV',
      'Generación de comprobantes en PDF',
    ],
    fechaInicio: '25 de Agosto',
    estado: 'disponible',
    creadoEn: '2026-08-10T00:00:00Z',
    actualizadoEn: '2026-09-30T00:00:00Z',
  },
  {
    id: '4',
    codigo: 'ANDES-SEC-04',
    titulo: 'Ciberseguridad Móvil, JWT & EAS Build en Nube',
    subtitulo: 'Protección de secretos, SSL Pinning y compilación de APK/AAB para tiendas',
    nivel: 'Avanzado',
    rating: 4.9,
    totalResenas: 67,
    duracion: '70 hrs',
    totalHorasAcademicas: 70,
    docente: 'Exar Williams Atao',
    docenteBio: 'Especialista en seguridad de aplicaciones móviles y DevOps de despliegue continuo con Expo EAS.',
    inversion: 159.90,
    precioRegular: 260.00,
    moneda: 'PEN',
    categoria: 'Seguridad',
    modalidad: 'Virtual en vivo',
    imagenUrl: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=800',
    descripcion: 'Protección de API Keys, sanitización de datos, autenticación con JWT y generación de paquetes APK/AAB con Expo EAS Build.',
    requisitos: [
      'Experiencia con APIs REST',
      'Uso de terminal Linux / macOS / Windows',
      'Control de versiones con Git',
    ],
    temario: [
      'Almacenamiento seguro de llaves criptográficas',
      'Firmado digital y sanitización de inputs',
      'Flujo de tokens de acceso y refresco (JWT)',
      'Compilación en la nube con EAS Build y despliegue a Play Store',
    ],
    fechaInicio: '30 de Agosto',
    estado: 'disponible',
    creadoEn: '2026-08-12T00:00:00Z',
    actualizadoEn: '2026-09-30T00:00:00Z',
  },
];
