// src/styles/boleta.styles.ts
// Estilos para el Modal de Boleta Electronica Digital con desglose de IGV (Modulo 09)

import { StyleSheet, Dimensions } from 'react-native';
import { Colors } from '../constants/Colors';

const { width } = Dimensions.get('window');

export const boletaStyles = StyleSheet.create({
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.82)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 18,
  },
  modalContainer: {
    width: '100%',
    maxHeight: '90%',
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.35,
    shadowRadius: 16,
    elevation: 10,
  },
  scrollContent: {
    padding: 20,
  },
  rucBox: {
    borderWidth: 2,
    borderColor: '#0F172A',
    borderRadius: 10,
    padding: 12,
    alignItems: 'center',
    marginBottom: 16,
    backgroundColor: '#F8FAFC',
  },
  rucTexto: {
    fontSize: 14,
    fontWeight: '800',
    color: '#0F172A',
    letterSpacing: 0.5,
  },
  boletaTipoTexto: {
    fontSize: 13,
    fontWeight: '700',
    color: '#0284C7',
    marginVertical: 4,
    textTransform: 'uppercase',
  },
  serieTexto: {
    fontSize: 16,
    fontWeight: '900',
    color: '#0F172A',
    letterSpacing: 1,
  },
  empresaHeader: {
    alignItems: 'center',
    marginBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#E2E8F0',
    paddingBottom: 12,
  },
  empresaNombre: {
    fontSize: 17,
    fontWeight: '900',
    color: '#0F172A',
    textAlign: 'center',
  },
  empresaSubtitulo: {
    fontSize: 11,
    color: '#64748B',
    marginTop: 2,
    textAlign: 'center',
  },
  empresaDireccion: {
    fontSize: 10,
    color: '#94A3B8',
    marginTop: 2,
    textAlign: 'center',
  },
  datosClienteCard: {
    backgroundColor: '#F8FAFC',
    borderRadius: 8,
    padding: 10,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  datoFila: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 4,
  },
  datoLabel: {
    fontSize: 11,
    color: '#64748B',
    fontWeight: '600',
  },
  datoValor: {
    fontSize: 11,
    color: '#0F172A',
    fontWeight: '700',
  },
  tablaItemsHeader: {
    flexDirection: 'row',
    backgroundColor: '#0F172A',
    borderRadius: 6,
    paddingVertical: 7,
    paddingHorizontal: 8,
    marginBottom: 6,
  },
  colDescripcionHeader: {
    flex: 3,
    fontSize: 11,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  colPrecioHeader: {
    flex: 1,
    fontSize: 11,
    fontWeight: '700',
    color: '#FFFFFF',
    textAlign: 'right',
  },
  itemFila: {
    flexDirection: 'row',
    paddingVertical: 8,
    paddingHorizontal: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
  },
  itemDescripcion: {
    flex: 3,
    fontSize: 12,
    color: '#1E293B',
    fontWeight: '600',
  },
  itemPrecio: {
    flex: 1,
    fontSize: 12,
    color: '#0F172A',
    fontWeight: '700',
    textAlign: 'right',
  },
  totalesContainer: {
    marginTop: 12,
    backgroundColor: '#F8FAFC',
    borderRadius: 10,
    padding: 12,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  totalFila: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 5,
  },
  totalLabel: {
    fontSize: 12,
    color: '#64748B',
    fontWeight: '600',
  },
  totalValor: {
    fontSize: 12,
    color: '#0F172A',
    fontWeight: '700',
  },
  totalFinalFila: {
    borderTopWidth: 1,
    borderTopColor: '#CBD5E1',
    paddingTop: 6,
    marginTop: 4,
  },
  totalFinalLabel: {
    fontSize: 14,
    color: '#0F172A',
    fontWeight: '900',
  },
  totalFinalValor: {
    fontSize: 16,
    color: '#059669',
    fontWeight: '900',
  },
  pagoDetalleCard: {
    marginTop: 12,
    padding: 10,
    borderRadius: 8,
    backgroundColor: '#F1F5F9',
  },
  pagoDetalleTexto: {
    fontSize: 11,
    color: '#475569',
    marginBottom: 2,
  },
  voucherMinicard: {
    marginTop: 8,
    padding: 8,
    borderRadius: 6,
    backgroundColor: '#E2E8F0',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  voucherMinicardTexto: {
    fontSize: 11,
    color: '#0284C7',
    fontWeight: '700',
  },
  botonesAccion: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 18,
    marginBottom: 6,
  },
  botonSecundario: {
    flex: 1,
    backgroundColor: '#F1F5F9',
    borderRadius: 10,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#CBD5E1',
  },
  botonSecundarioTexto: {
    fontSize: 13,
    fontWeight: '700',
    color: '#475569',
  },
  botonPrimario: {
    flex: 1,
    backgroundColor: '#0284C7',
    borderRadius: 10,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  botonPrimarioTexto: {
    fontSize: 13,
    fontWeight: '700',
    color: '#FFFFFF',
  },
});
